//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BP2Projekat
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORMA
    {
        public int FORM_ID { get; set; }
        public string DAT_ISP { get; set; }
        public string OPIS_OST { get; set; }
        public string DOD_MOLBA { get; set; }
        public int SLUZBENIKMBR { get; set; }
        public Nullable<int> MUSTERIJAMUS_ID { get; set; }
    
        public virtual SLUZBENIK SLUZBENIK { get; set; }
        public virtual MUSTERIJA MUSTERIJA { get; set; }
    }
}
