//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BP2Projekat
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOBILNI_TELEFON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MOBILNI_TELEFON()
        {
            this.OSTECENJEs = new HashSet<OSTECENJE>();
        }
    
        public int MOB_ID { get; set; }
        public string MODEL { get; set; }
        public string PROIZV { get; set; }
        public string OP_SIS { get; set; }
        public int MUSTERIJAMUS_ID { get; set; }
    
        public virtual MUSTERIJA MUSTERIJA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OSTECENJE> OSTECENJEs { get; set; }
    }
}
