//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BP2Projekat
{
    using System;
    using System.Collections.Generic;
    
    public partial class NABAVKA
    {
        public int CENA { get; set; }
        public int SLUZBENIKMBR { get; set; }
        public int TELEFONSKI_DEOID_DEO { get; set; }
        public Nullable<int> POPRAVKAOSTECENJEOST_ID { get; set; }
        public Nullable<int> POPRAVKAOSTECENJEMOBILNI_TELEFONMOB_ID { get; set; }
        public Nullable<int> POPRAVKASERVISERMBR { get; set; }
    
        public virtual SLUZBENIK SLUZBENIK { get; set; }
        public virtual TELEFONSKI_DEO TELEFONSKI_DEO { get; set; }
        public virtual POPRAVKA POPRAVKA { get; set; }
    }
}
