//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BP2Projekat
{
    using System;
    using System.Collections.Generic;
    
    public partial class OSTECENJE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OSTECENJE()
        {
            this.POPRAVKAs = new HashSet<POPRAVKA>();
        }
    
        public int OST_ID { get; set; }
        public string OPIS_OST { get; set; }
        public string TIP_OST { get; set; }
        public int MOBILNI_TELEFONMOB_ID { get; set; }
    
        public virtual MOBILNI_TELEFON MOBILNI_TELEFON { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POPRAVKA> POPRAVKAs { get; set; }
    }
}
