//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BP2Projekat
{
    using System;
    using System.Collections.Generic;
    
    public partial class POPRAVKA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public POPRAVKA()
        {
            this.NABAVKAs = new HashSet<NABAVKA>();
        }
    
        public int CENA { get; set; }
        public int OSTECENJEOST_ID { get; set; }
        public int OSTECENJEMOBILNI_TELEFONMOB_ID { get; set; }
        public int SERVISERMBR { get; set; }
    
        public virtual OSTECENJE OSTECENJE { get; set; }
        public virtual SERVISER SERVISER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NABAVKA> NABAVKAs { get; set; }
    }
}
