//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BP2Projekat
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROIZVODNJA
    {
        public int TELEFONSKI_DEOID_DEO { get; set; }
        public int PROIZVODJACID_PROIZV { get; set; }
    
        public virtual TELEFONSKI_DEO TELEFONSKI_DEO { get; set; }
        public virtual PROIZVODJAC PROIZVODJAC { get; set; }
    }
}
