
-- --------------------------------------------------
-- Entity Designer DDL Script for SQL Server 2005, 2008, 2012 and Azure
-- --------------------------------------------------
-- Date Created: 05/29/2021 23:30:53
-- Generated from EDMX file: E:\4 Godina\Baze 2\MojProjekat\BP2Projekat\BP2Projekat\ProjekatModelDB.edmx
-- --------------------------------------------------

SET QUOTED_IDENTIFIER OFF;
GO
USE [BP2ProjekatDB];
GO
IF SCHEMA_ID(N'dbo') IS NULL EXECUTE(N'CREATE SCHEMA [dbo]');
GO

-- --------------------------------------------------
-- Dropping existing FOREIGN KEY constraints
-- --------------------------------------------------

IF OBJECT_ID(N'[dbo].[FK_SERVISRADNIK]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[RADNICI] DROP CONSTRAINT [FK_SERVISRADNIK];
GO
IF OBJECT_ID(N'[dbo].[FK_SERVISSERVISNI_ALAT]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[SERVISNI_ALATI] DROP CONSTRAINT [FK_SERVISSERVISNI_ALAT];
GO
IF OBJECT_ID(N'[dbo].[FK_SLUZBENIKFORMA]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[FORME] DROP CONSTRAINT [FK_SLUZBENIKFORMA];
GO
IF OBJECT_ID(N'[dbo].[FK_SERVISERSERVISNI_ALAT]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[SERVISNI_ALATI] DROP CONSTRAINT [FK_SERVISERSERVISNI_ALAT];
GO
IF OBJECT_ID(N'[dbo].[FK_MUSTERIJAMOBILNI_TELEFON]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[MOBILNI_TELEFONI] DROP CONSTRAINT [FK_MUSTERIJAMOBILNI_TELEFON];
GO
IF OBJECT_ID(N'[dbo].[FK_MUSTERIJAFORMA]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[FORME] DROP CONSTRAINT [FK_MUSTERIJAFORMA];
GO
IF OBJECT_ID(N'[dbo].[FK_MOBILNI_TELEFONOSTECENJE]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[OSTECENJA] DROP CONSTRAINT [FK_MOBILNI_TELEFONOSTECENJE];
GO
IF OBJECT_ID(N'[dbo].[FK_TELEFONSKI_DEOPROIZVODNJA]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[PROIZVODNJAs] DROP CONSTRAINT [FK_TELEFONSKI_DEOPROIZVODNJA];
GO
IF OBJECT_ID(N'[dbo].[FK_PROIZVODNJAPROIZVODJAC]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[PROIZVODNJAs] DROP CONSTRAINT [FK_PROIZVODNJAPROIZVODJAC];
GO
IF OBJECT_ID(N'[dbo].[FK_OSTECENJEPOPRAVKA]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[POPRAVKAs] DROP CONSTRAINT [FK_OSTECENJEPOPRAVKA];
GO
IF OBJECT_ID(N'[dbo].[FK_SERVISERPOPRAVKA]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[POPRAVKAs] DROP CONSTRAINT [FK_SERVISERPOPRAVKA];
GO
IF OBJECT_ID(N'[dbo].[FK_SLUZBENIKNABAVKA]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[NABAVKAs] DROP CONSTRAINT [FK_SLUZBENIKNABAVKA];
GO
IF OBJECT_ID(N'[dbo].[FK_TELEFONSKI_DEONABAVKA]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[NABAVKAs] DROP CONSTRAINT [FK_TELEFONSKI_DEONABAVKA];
GO
IF OBJECT_ID(N'[dbo].[FK_NABAVKAPOPRAVKA]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[NABAVKAs] DROP CONSTRAINT [FK_NABAVKAPOPRAVKA];
GO
IF OBJECT_ID(N'[dbo].[FK_RADNIKRADNIK]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[RADNICI] DROP CONSTRAINT [FK_RADNIKRADNIK];
GO
IF OBJECT_ID(N'[dbo].[FK_SLUZBENIK_inherits_RADNIK]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[RADNICI_SLUZBENIK] DROP CONSTRAINT [FK_SLUZBENIK_inherits_RADNIK];
GO
IF OBJECT_ID(N'[dbo].[FK_SERVISER_inherits_RADNIK]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[RADNICI_SERVISER] DROP CONSTRAINT [FK_SERVISER_inherits_RADNIK];
GO

-- --------------------------------------------------
-- Dropping existing tables
-- --------------------------------------------------

IF OBJECT_ID(N'[dbo].[SERVIS1]', 'U') IS NOT NULL
    DROP TABLE [dbo].[SERVIS1];
GO
IF OBJECT_ID(N'[dbo].[RADNICI]', 'U') IS NOT NULL
    DROP TABLE [dbo].[RADNICI];
GO
IF OBJECT_ID(N'[dbo].[SERVISNI_ALATI]', 'U') IS NOT NULL
    DROP TABLE [dbo].[SERVISNI_ALATI];
GO
IF OBJECT_ID(N'[dbo].[MUSTERIJE]', 'U') IS NOT NULL
    DROP TABLE [dbo].[MUSTERIJE];
GO
IF OBJECT_ID(N'[dbo].[MOBILNI_TELEFONI]', 'U') IS NOT NULL
    DROP TABLE [dbo].[MOBILNI_TELEFONI];
GO
IF OBJECT_ID(N'[dbo].[OSTECENJA]', 'U') IS NOT NULL
    DROP TABLE [dbo].[OSTECENJA];
GO
IF OBJECT_ID(N'[dbo].[FORME]', 'U') IS NOT NULL
    DROP TABLE [dbo].[FORME];
GO
IF OBJECT_ID(N'[dbo].[TELEFONSKI_DELOVI]', 'U') IS NOT NULL
    DROP TABLE [dbo].[TELEFONSKI_DELOVI];
GO
IF OBJECT_ID(N'[dbo].[PROIZVODJACI]', 'U') IS NOT NULL
    DROP TABLE [dbo].[PROIZVODJACI];
GO
IF OBJECT_ID(N'[dbo].[PROIZVODNJAs]', 'U') IS NOT NULL
    DROP TABLE [dbo].[PROIZVODNJAs];
GO
IF OBJECT_ID(N'[dbo].[POPRAVKAs]', 'U') IS NOT NULL
    DROP TABLE [dbo].[POPRAVKAs];
GO
IF OBJECT_ID(N'[dbo].[NABAVKAs]', 'U') IS NOT NULL
    DROP TABLE [dbo].[NABAVKAs];
GO
IF OBJECT_ID(N'[dbo].[RADNICI_SLUZBENIK]', 'U') IS NOT NULL
    DROP TABLE [dbo].[RADNICI_SLUZBENIK];
GO
IF OBJECT_ID(N'[dbo].[RADNICI_SERVISER]', 'U') IS NOT NULL
    DROP TABLE [dbo].[RADNICI_SERVISER];
GO

-- --------------------------------------------------
-- Creating all tables
-- --------------------------------------------------

-- Creating table 'SERVIS1'
CREATE TABLE [dbo].[SERVIS1] (
    [SERV_ID] int IDENTITY(1,1) NOT NULL,
    [WEB_STR] nvarchar(max)  NOT NULL,
    [BR_ZAP] int  NOT NULL,
    [TELBROJ] int  NOT NULL,
    [ADRESA] nvarchar(max)  NOT NULL,
    [RAD_VRM] nvarchar(max)  NOT NULL
);
GO

-- Creating table 'RADNICI'
CREATE TABLE [dbo].[RADNICI] (
    [MBR] int IDENTITY(1,1) NOT NULL,
    [PLT] int  NOT NULL,
    [IME] nvarchar(max)  NOT NULL,
    [PRZ] nvarchar(max)  NOT NULL,
    [SERVISSERV_ID] int  NULL,
    [RADNIKMBR] int  NULL
);
GO

-- Creating table 'SERVISNI_ALATI'
CREATE TABLE [dbo].[SERVISNI_ALATI] (
    [ALAT_ID] int IDENTITY(1,1) NOT NULL,
    [NAZ] nvarchar(max)  NOT NULL,
    [TIP] nvarchar(max)  NOT NULL,
    [SERVISSERV_ID] int  NOT NULL,
    [KLC] int  NOT NULL,
    [SERVISERMBR] int  NULL
);
GO

-- Creating table 'MUSTERIJE'
CREATE TABLE [dbo].[MUSTERIJE] (
    [MUS_ID] int IDENTITY(1,1) NOT NULL,
    [IME] nvarchar(max)  NOT NULL,
    [PRZ] nvarchar(max)  NOT NULL,
    [BR_TEL] int  NOT NULL,
    [EMAIL] nvarchar(max)  NOT NULL
);
GO

-- Creating table 'MOBILNI_TELEFONI'
CREATE TABLE [dbo].[MOBILNI_TELEFONI] (
    [MOB_ID] int IDENTITY(1,1) NOT NULL,
    [MODEL] nvarchar(max)  NOT NULL,
    [PROIZV] nvarchar(max)  NOT NULL,
    [OP_SIS] nvarchar(max)  NOT NULL,
    [MUSTERIJAMUS_ID] int  NOT NULL
);
GO

-- Creating table 'OSTECENJA'
CREATE TABLE [dbo].[OSTECENJA] (
    [OST_ID] int IDENTITY(1,1) NOT NULL,
    [OPIS_OST] nvarchar(max)  NOT NULL,
    [TIP_OST] nvarchar(max)  NOT NULL,
    [MOBILNI_TELEFONMOB_ID] int  NOT NULL
);
GO

-- Creating table 'FORME'
CREATE TABLE [dbo].[FORME] (
    [FORM_ID] int IDENTITY(1,1) NOT NULL,
    [DAT_ISP] nvarchar(max)  NOT NULL,
    [OPIS_OST] nvarchar(max)  NOT NULL,
    [DOD_MOLBA] nvarchar(max)  NOT NULL,
    [SLUZBENIKMBR] int  NOT NULL,
    [MUSTERIJAMUS_ID] int  NULL
);
GO

-- Creating table 'TELEFONSKI_DELOVI'
CREATE TABLE [dbo].[TELEFONSKI_DELOVI] (
    [ID_DEO] int IDENTITY(1,1) NOT NULL,
    [TIP] nvarchar(max)  NOT NULL,
    [ORIG] bit  NOT NULL
);
GO

-- Creating table 'PROIZVODJACI'
CREATE TABLE [dbo].[PROIZVODJACI] (
    [ID_PROIZV] int IDENTITY(1,1) NOT NULL,
    [NAZ] nvarchar(max)  NOT NULL,
    [TELBROJ] int  NOT NULL
);
GO

-- Creating table 'PROIZVODNJAs'
CREATE TABLE [dbo].[PROIZVODNJAs] (
    [TELEFONSKI_DEOID_DEO] int  NOT NULL,
    [PROIZVODJACID_PROIZV] int  NOT NULL
);
GO

-- Creating table 'POPRAVKAs'
CREATE TABLE [dbo].[POPRAVKAs] (
    [CENA] int  NOT NULL,
    [OSTECENJEOST_ID] int  NOT NULL,
    [OSTECENJEMOBILNI_TELEFONMOB_ID] int  NOT NULL,
    [SERVISERMBR] int  NOT NULL
);
GO

-- Creating table 'NABAVKAs'
CREATE TABLE [dbo].[NABAVKAs] (
    [CENA] int  NOT NULL,
    [SLUZBENIKMBR] int  NOT NULL,
    [TELEFONSKI_DEOID_DEO] int  NOT NULL,
    [POPRAVKAOSTECENJEOST_ID] int  NULL,
    [POPRAVKAOSTECENJEMOBILNI_TELEFONMOB_ID] int  NULL,
    [POPRAVKASERVISERMBR] int  NULL
);
GO

-- Creating table 'RADNICI_SLUZBENIK'
CREATE TABLE [dbo].[RADNICI_SLUZBENIK] (
    [MBR] int  NOT NULL
);
GO

-- Creating table 'RADNICI_SERVISER'
CREATE TABLE [dbo].[RADNICI_SERVISER] (
    [MBR] int  NOT NULL
);
GO

-- --------------------------------------------------
-- Creating all PRIMARY KEY constraints
-- --------------------------------------------------

-- Creating primary key on [SERV_ID] in table 'SERVIS1'
ALTER TABLE [dbo].[SERVIS1]
ADD CONSTRAINT [PK_SERVIS1]
    PRIMARY KEY CLUSTERED ([SERV_ID] ASC);
GO

-- Creating primary key on [MBR] in table 'RADNICI'
ALTER TABLE [dbo].[RADNICI]
ADD CONSTRAINT [PK_RADNICI]
    PRIMARY KEY CLUSTERED ([MBR] ASC);
GO

-- Creating primary key on [ALAT_ID] in table 'SERVISNI_ALATI'
ALTER TABLE [dbo].[SERVISNI_ALATI]
ADD CONSTRAINT [PK_SERVISNI_ALATI]
    PRIMARY KEY CLUSTERED ([ALAT_ID] ASC);
GO

-- Creating primary key on [MUS_ID] in table 'MUSTERIJE'
ALTER TABLE [dbo].[MUSTERIJE]
ADD CONSTRAINT [PK_MUSTERIJE]
    PRIMARY KEY CLUSTERED ([MUS_ID] ASC);
GO

-- Creating primary key on [MOB_ID] in table 'MOBILNI_TELEFONI'
ALTER TABLE [dbo].[MOBILNI_TELEFONI]
ADD CONSTRAINT [PK_MOBILNI_TELEFONI]
    PRIMARY KEY CLUSTERED ([MOB_ID] ASC);
GO

-- Creating primary key on [OST_ID], [MOBILNI_TELEFONMOB_ID] in table 'OSTECENJA'
ALTER TABLE [dbo].[OSTECENJA]
ADD CONSTRAINT [PK_OSTECENJA]
    PRIMARY KEY CLUSTERED ([OST_ID], [MOBILNI_TELEFONMOB_ID] ASC);
GO

-- Creating primary key on [FORM_ID] in table 'FORME'
ALTER TABLE [dbo].[FORME]
ADD CONSTRAINT [PK_FORME]
    PRIMARY KEY CLUSTERED ([FORM_ID] ASC);
GO

-- Creating primary key on [ID_DEO] in table 'TELEFONSKI_DELOVI'
ALTER TABLE [dbo].[TELEFONSKI_DELOVI]
ADD CONSTRAINT [PK_TELEFONSKI_DELOVI]
    PRIMARY KEY CLUSTERED ([ID_DEO] ASC);
GO

-- Creating primary key on [ID_PROIZV] in table 'PROIZVODJACI'
ALTER TABLE [dbo].[PROIZVODJACI]
ADD CONSTRAINT [PK_PROIZVODJACI]
    PRIMARY KEY CLUSTERED ([ID_PROIZV] ASC);
GO

-- Creating primary key on [TELEFONSKI_DEOID_DEO], [PROIZVODJACID_PROIZV] in table 'PROIZVODNJAs'
ALTER TABLE [dbo].[PROIZVODNJAs]
ADD CONSTRAINT [PK_PROIZVODNJAs]
    PRIMARY KEY CLUSTERED ([TELEFONSKI_DEOID_DEO], [PROIZVODJACID_PROIZV] ASC);
GO

-- Creating primary key on [OSTECENJEOST_ID], [OSTECENJEMOBILNI_TELEFONMOB_ID], [SERVISERMBR] in table 'POPRAVKAs'
ALTER TABLE [dbo].[POPRAVKAs]
ADD CONSTRAINT [PK_POPRAVKAs]
    PRIMARY KEY CLUSTERED ([OSTECENJEOST_ID], [OSTECENJEMOBILNI_TELEFONMOB_ID], [SERVISERMBR] ASC);
GO

-- Creating primary key on [TELEFONSKI_DEOID_DEO], [SLUZBENIKMBR] in table 'NABAVKAs'
ALTER TABLE [dbo].[NABAVKAs]
ADD CONSTRAINT [PK_NABAVKAs]
    PRIMARY KEY CLUSTERED ([TELEFONSKI_DEOID_DEO], [SLUZBENIKMBR] ASC);
GO

-- Creating primary key on [MBR] in table 'RADNICI_SLUZBENIK'
ALTER TABLE [dbo].[RADNICI_SLUZBENIK]
ADD CONSTRAINT [PK_RADNICI_SLUZBENIK]
    PRIMARY KEY CLUSTERED ([MBR] ASC);
GO

-- Creating primary key on [MBR] in table 'RADNICI_SERVISER'
ALTER TABLE [dbo].[RADNICI_SERVISER]
ADD CONSTRAINT [PK_RADNICI_SERVISER]
    PRIMARY KEY CLUSTERED ([MBR] ASC);
GO

-- --------------------------------------------------
-- Creating all FOREIGN KEY constraints
-- --------------------------------------------------

-- Creating foreign key on [SERVISSERV_ID] in table 'RADNICI'
ALTER TABLE [dbo].[RADNICI]
ADD CONSTRAINT [FK_SERVISRADNIK]
    FOREIGN KEY ([SERVISSERV_ID])
    REFERENCES [dbo].[SERVIS1]
        ([SERV_ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_SERVISRADNIK'
CREATE INDEX [IX_FK_SERVISRADNIK]
ON [dbo].[RADNICI]
    ([SERVISSERV_ID]);
GO

-- Creating foreign key on [SERVISSERV_ID] in table 'SERVISNI_ALATI'
ALTER TABLE [dbo].[SERVISNI_ALATI]
ADD CONSTRAINT [FK_SERVISSERVISNI_ALAT]
    FOREIGN KEY ([SERVISSERV_ID])
    REFERENCES [dbo].[SERVIS1]
        ([SERV_ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_SERVISSERVISNI_ALAT'
CREATE INDEX [IX_FK_SERVISSERVISNI_ALAT]
ON [dbo].[SERVISNI_ALATI]
    ([SERVISSERV_ID]);
GO

-- Creating foreign key on [SLUZBENIKMBR] in table 'FORME'
ALTER TABLE [dbo].[FORME]
ADD CONSTRAINT [FK_SLUZBENIKFORMA]
    FOREIGN KEY ([SLUZBENIKMBR])
    REFERENCES [dbo].[RADNICI_SLUZBENIK]
        ([MBR])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_SLUZBENIKFORMA'
CREATE INDEX [IX_FK_SLUZBENIKFORMA]
ON [dbo].[FORME]
    ([SLUZBENIKMBR]);
GO

-- Creating foreign key on [SERVISERMBR] in table 'SERVISNI_ALATI'
ALTER TABLE [dbo].[SERVISNI_ALATI]
ADD CONSTRAINT [FK_SERVISERSERVISNI_ALAT]
    FOREIGN KEY ([SERVISERMBR])
    REFERENCES [dbo].[RADNICI_SERVISER]
        ([MBR])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_SERVISERSERVISNI_ALAT'
CREATE INDEX [IX_FK_SERVISERSERVISNI_ALAT]
ON [dbo].[SERVISNI_ALATI]
    ([SERVISERMBR]);
GO

-- Creating foreign key on [MUSTERIJAMUS_ID] in table 'MOBILNI_TELEFONI'
ALTER TABLE [dbo].[MOBILNI_TELEFONI]
ADD CONSTRAINT [FK_MUSTERIJAMOBILNI_TELEFON]
    FOREIGN KEY ([MUSTERIJAMUS_ID])
    REFERENCES [dbo].[MUSTERIJE]
        ([MUS_ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_MUSTERIJAMOBILNI_TELEFON'
CREATE INDEX [IX_FK_MUSTERIJAMOBILNI_TELEFON]
ON [dbo].[MOBILNI_TELEFONI]
    ([MUSTERIJAMUS_ID]);
GO

-- Creating foreign key on [MUSTERIJAMUS_ID] in table 'FORME'
ALTER TABLE [dbo].[FORME]
ADD CONSTRAINT [FK_MUSTERIJAFORMA]
    FOREIGN KEY ([MUSTERIJAMUS_ID])
    REFERENCES [dbo].[MUSTERIJE]
        ([MUS_ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_MUSTERIJAFORMA'
CREATE INDEX [IX_FK_MUSTERIJAFORMA]
ON [dbo].[FORME]
    ([MUSTERIJAMUS_ID]);
GO

-- Creating foreign key on [MOBILNI_TELEFONMOB_ID] in table 'OSTECENJA'
ALTER TABLE [dbo].[OSTECENJA]
ADD CONSTRAINT [FK_MOBILNI_TELEFONOSTECENJE]
    FOREIGN KEY ([MOBILNI_TELEFONMOB_ID])
    REFERENCES [dbo].[MOBILNI_TELEFONI]
        ([MOB_ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_MOBILNI_TELEFONOSTECENJE'
CREATE INDEX [IX_FK_MOBILNI_TELEFONOSTECENJE]
ON [dbo].[OSTECENJA]
    ([MOBILNI_TELEFONMOB_ID]);
GO

-- Creating foreign key on [TELEFONSKI_DEOID_DEO] in table 'PROIZVODNJAs'
ALTER TABLE [dbo].[PROIZVODNJAs]
ADD CONSTRAINT [FK_TELEFONSKI_DEOPROIZVODNJA]
    FOREIGN KEY ([TELEFONSKI_DEOID_DEO])
    REFERENCES [dbo].[TELEFONSKI_DELOVI]
        ([ID_DEO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating foreign key on [PROIZVODJACID_PROIZV] in table 'PROIZVODNJAs'
ALTER TABLE [dbo].[PROIZVODNJAs]
ADD CONSTRAINT [FK_PROIZVODNJAPROIZVODJAC]
    FOREIGN KEY ([PROIZVODJACID_PROIZV])
    REFERENCES [dbo].[PROIZVODJACI]
        ([ID_PROIZV])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_PROIZVODNJAPROIZVODJAC'
CREATE INDEX [IX_FK_PROIZVODNJAPROIZVODJAC]
ON [dbo].[PROIZVODNJAs]
    ([PROIZVODJACID_PROIZV]);
GO

-- Creating foreign key on [OSTECENJEOST_ID], [OSTECENJEMOBILNI_TELEFONMOB_ID] in table 'POPRAVKAs'
ALTER TABLE [dbo].[POPRAVKAs]
ADD CONSTRAINT [FK_OSTECENJEPOPRAVKA]
    FOREIGN KEY ([OSTECENJEOST_ID], [OSTECENJEMOBILNI_TELEFONMOB_ID])
    REFERENCES [dbo].[OSTECENJA]
        ([OST_ID], [MOBILNI_TELEFONMOB_ID])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating foreign key on [SERVISERMBR] in table 'POPRAVKAs'
ALTER TABLE [dbo].[POPRAVKAs]
ADD CONSTRAINT [FK_SERVISERPOPRAVKA]
    FOREIGN KEY ([SERVISERMBR])
    REFERENCES [dbo].[RADNICI_SERVISER]
        ([MBR])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_SERVISERPOPRAVKA'
CREATE INDEX [IX_FK_SERVISERPOPRAVKA]
ON [dbo].[POPRAVKAs]
    ([SERVISERMBR]);
GO

-- Creating foreign key on [SLUZBENIKMBR] in table 'NABAVKAs'
ALTER TABLE [dbo].[NABAVKAs]
ADD CONSTRAINT [FK_SLUZBENIKNABAVKA]
    FOREIGN KEY ([SLUZBENIKMBR])
    REFERENCES [dbo].[RADNICI_SLUZBENIK]
        ([MBR])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_SLUZBENIKNABAVKA'
CREATE INDEX [IX_FK_SLUZBENIKNABAVKA]
ON [dbo].[NABAVKAs]
    ([SLUZBENIKMBR]);
GO

-- Creating foreign key on [TELEFONSKI_DEOID_DEO] in table 'NABAVKAs'
ALTER TABLE [dbo].[NABAVKAs]
ADD CONSTRAINT [FK_TELEFONSKI_DEONABAVKA]
    FOREIGN KEY ([TELEFONSKI_DEOID_DEO])
    REFERENCES [dbo].[TELEFONSKI_DELOVI]
        ([ID_DEO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating foreign key on [POPRAVKAOSTECENJEOST_ID], [POPRAVKAOSTECENJEMOBILNI_TELEFONMOB_ID], [POPRAVKASERVISERMBR] in table 'NABAVKAs'
ALTER TABLE [dbo].[NABAVKAs]
ADD CONSTRAINT [FK_NABAVKAPOPRAVKA]
    FOREIGN KEY ([POPRAVKAOSTECENJEOST_ID], [POPRAVKAOSTECENJEMOBILNI_TELEFONMOB_ID], [POPRAVKASERVISERMBR])
    REFERENCES [dbo].[POPRAVKAs]
        ([OSTECENJEOST_ID], [OSTECENJEMOBILNI_TELEFONMOB_ID], [SERVISERMBR])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_NABAVKAPOPRAVKA'
CREATE INDEX [IX_FK_NABAVKAPOPRAVKA]
ON [dbo].[NABAVKAs]
    ([POPRAVKAOSTECENJEOST_ID], [POPRAVKAOSTECENJEMOBILNI_TELEFONMOB_ID], [POPRAVKASERVISERMBR]);
GO

-- Creating foreign key on [RADNIKMBR] in table 'RADNICI'
ALTER TABLE [dbo].[RADNICI]
ADD CONSTRAINT [FK_RADNIKRADNIK]
    FOREIGN KEY ([RADNIKMBR])
    REFERENCES [dbo].[RADNICI]
        ([MBR])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_RADNIKRADNIK'
CREATE INDEX [IX_FK_RADNIKRADNIK]
ON [dbo].[RADNICI]
    ([RADNIKMBR]);
GO

-- Creating foreign key on [MBR] in table 'RADNICI_SLUZBENIK'
ALTER TABLE [dbo].[RADNICI_SLUZBENIK]
ADD CONSTRAINT [FK_SLUZBENIK_inherits_RADNIK]
    FOREIGN KEY ([MBR])
    REFERENCES [dbo].[RADNICI]
        ([MBR])
    ON DELETE CASCADE ON UPDATE NO ACTION;
GO

-- Creating foreign key on [MBR] in table 'RADNICI_SERVISER'
ALTER TABLE [dbo].[RADNICI_SERVISER]
ADD CONSTRAINT [FK_SERVISER_inherits_RADNIK]
    FOREIGN KEY ([MBR])
    REFERENCES [dbo].[RADNICI]
        ([MBR])
    ON DELETE CASCADE ON UPDATE NO ACTION;
GO

-- --------------------------------------------------
-- Script has ended
-- --------------------------------------------------