//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BP2Projekat
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjekatModelDBContext : DbContext
    {
        public ProjekatModelDBContext()
            : base("name=ProjekatModelDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SERVIS> SERVIS1 { get; set; }
        public virtual DbSet<RADNIK> RADNICI { get; set; }
        public virtual DbSet<SERVISNI_ALAT> SERVISNI_ALATI { get; set; }
        public virtual DbSet<MUSTERIJA> MUSTERIJE { get; set; }
        public virtual DbSet<MOBILNI_TELEFON> MOBILNI_TELEFONI { get; set; }
        public virtual DbSet<OSTECENJE> OSTECENJA { get; set; }
        public virtual DbSet<FORMA> FORME { get; set; }
        public virtual DbSet<TELEFONSKI_DEO> TELEFONSKI_DELOVI { get; set; }
        public virtual DbSet<PROIZVODJAC> PROIZVODJACI { get; set; }
        public virtual DbSet<PROIZVODNJA> PROIZVODNJAs { get; set; }
        public virtual DbSet<POPRAVKA> POPRAVKAs { get; set; }
        public virtual DbSet<NABAVKA> NABAVKAs { get; set; }
    }
}
