//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BP2Projekat
{
    using System;
    using System.Collections.Generic;
    
    public partial class RADNIK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RADNIK()
        {
            this.PODREDJENI = new HashSet<RADNIK>();
        }
    
        public int MBR { get; set; }
        public int PLT { get; set; }
        public string IME { get; set; }
        public string PRZ { get; set; }
        public Nullable<int> SERVISSERV_ID { get; set; }
        public Nullable<int> RADNIKMBR { get; set; }
    
        public virtual SERVIS SERVIS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RADNIK> PODREDJENI { get; set; }
        public virtual RADNIK NADREDJEN { get; set; }
    }
}
