//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BP2Projekat
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVISNI_ALAT
    {
        public int ALAT_ID { get; set; }
        public string NAZ { get; set; }
        public string TIP { get; set; }
        public int SERVISSERV_ID { get; set; }
        public int KLC { get; set; }
        public Nullable<int> SERVISERMBR { get; set; }
    
        public virtual SERVIS SERVIS { get; set; }
        public virtual SERVISER SERVISER { get; set; }
    }
}
