//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BP2Projekat
{
    using System;
    using System.Collections.Generic;
    
    public partial class TELEFONSKI_DEO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TELEFONSKI_DEO()
        {
            this.PROIZVODNJAs = new HashSet<PROIZVODNJA>();
            this.NABAVKAs = new HashSet<NABAVKA>();
        }
    
        public int ID_DEO { get; set; }
        public string TIP { get; set; }
        public bool ORIG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROIZVODNJA> PROIZVODNJAs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NABAVKA> NABAVKAs { get; set; }
    }
}
