/****** Script for SelectTopNRows command from SSMS  ******/
CREATE PROCEDURE GetSluzbeniciIDs
AS
BEGIN TRY
	SELECT MBR FROM [dbo].[RADNICI_SLUZBENIK]
END TRY
BEGIN CATCH
	SELECT
	ERROR_NUMBER() AS ErrorNumber
	,ERROR_MESSAGE() AS ErrorMessage;
END CATCH

CREATE PROCEDURE GetServiseriIDs
AS
BEGIN TRY
	SELECT MBR FROM [dbo].[RADNICI_SERVISER]
END TRY
BEGIN CATCH
	SELECT
	ERROR_NUMBER() AS ErrorNumber
	,ERROR_MESSAGE() AS ErrorMessage;
END CATCH